### ISSUE TITLE
Fix searchType timing bug

### ISSUE THREAD

**Issue by Luke-G-Cordova** [Luke-G-Cordova/BetterSearch#21]
This bug crashes the extension. The error log is as follows and only happens sometimes.
```
Uncaught TypeError: Cannot read properties of null (reading 'searchType')
    at Input (contentScript.js:270:69)
    at renderWithHooks (contentScript.js:37216:18)
    at mountIndeterminateComponent (contentScript.js:40980:13)
    at beginWork (contentScript.js:42493:16)
    at beginWork$1 (contentScript.js:48332:14)
    at performUnitOfWork (contentScript.js:47466:12)
    at workLoopSync (contentScript.js:47372:5)
    at renderRootSync (contentScript.js:47340:7)
    at recoverFromConcurrentError (contentScript.js:46756:20)
    at performSyncWorkOnRoot (contentScript.js:47002:20)
```

**Comment by Luke-G-Cordova** [comment]
Leaving this issue open incase #22 is not a permanent fix.
